language: node_js
addons:
  sonarcloud:
    organization: loopingz-github
node_js:
- '6'
script:
- npm run test
after_success:
- sonar-scanner
before_deploy:
- npm run build
- npm install -g bower
- bower install
deploy:
  provider: npm
  email: rcattiau@loopingz.com
  skip_cleanup: true
  tag: next
  on:
    tags: true
  api_key:
    secure: C3ptKWGX5Q8FshLZeBe6KoIJXjgD+kr7RnGpmHDCXaXMOQjZ7QWxX49V8uIBD6d6oCl9BcGlSR+BwiRD/JpJxXjDDj+twXdQUw1Y9NhA5JSQkk8yEnOKHQ70k5XGt5O6Sg+SCHQoL7JyLN6UMR9KIJIJfw41m5DI42O9ENgsLEjFaIPciATe/QJeUPYI26qtVEOoXAgtzGxvvFC6DENAjvndk3nFid5aG65iKiwyLkYxlVwkBjIPxMDeCVKYUubKDSyLge5gZe72PNxA5c9XTuAO2SL9rUhc43ucsFPJsragWApdhu+T/uKqzBIDJ5ezOKe3w7yIf9gBi7CN1YYM755fTOTnWKQdEklrzVPuFyHoCDIdjFM2UvZ4t7TuQgo4wOBhmEZORWWxnwBbKU6lw5cUf9Esvs5p/nBoJNoHdbQgkQ4pD1ChiIzGnitd4o47+xw6vAnr5qkDOqZc9DskgHmqhQa8je+auGNBn6Nw0CvpYXU5L6ZLOA0iluVg9KW5efLbTdNbCw6571ABRpO8yfsTzG8MXqgPsK+rwlu92G0FTSl7TvKI2uL/yjDR2Y0QOcHqX6AERRn0VgqjLPUFh8SqaIWDlwkevgMj+bYBweGIcK12ykKiQueprtHMoRmy8B8gsm6omEIYJjXfA/7PNWw7NYO1woKC9Lf1Jki4UH0=
