language: node_js
addons:
  sonarcloud:
    organization: loopingz-github
node_js:
- '8'
script:
- npm run test
after_success:
- sonar-scanner
before_deploy:
- npm run build
- npm install -g bower
- bower install
- cp -r node_modules/xterm/dist app/bower_components/xterm
deploy:
  provider: npm
  email: rcattiau@loopingz.com
  skip_cleanup: true
  tag: next
  on:
    tags: true
  api_key:
    secure: rg2Bl5WCAYfm84MEoSLnWWuLB46wirGUCcdGZkBcHSnZ6WZBq9zz2C7s8XVE6qyQbBUgbE6WV2RpYcJTSQ7ziqzGa5HMhVEVzbLa6vbDQ1ApxfoAJ7rzKtEliPC+1Ttm1ZJv+y9wokw/51PaTyxvTgYVmcWi1I+NjCcfTO0K5P1G/F1F9UT+F014SBaTEGSUKnHhbSWDFIGIfq4w7SrzXZwOZVCDOc7LmlcIx+I+vVOfyQ4cNHZq6xPm7Q4jM8PWkeZrAk9ItGRVYRJksz7wtEjWtOIpdsDM0kH2myTI3iw756dCuYqyzfloRO9fhhHE4qtbeQjZZz+6jtsThx+irUwTj+m7Gzzx2/vqkIMxr6+Gcj9vKIlWhU0pEdta8BeaBUaprdHIuwW3ODSNJko+xgMHJegNxRs4bLbHpk04wBAD/pX6vB6KHJMVKFN+5x5RgxPEM4T7bpyBHR5CJsUM1CvA1sGSgq2p8CSRUa/638viTX7znPIz1ywTGIJ83X4LDyrOgbfE5IxYrDZudzhKJwOQm5xY2d4o2aoNq6zQ3IArj06zJ0ndS8b+QAxDwMkAiAzGZ96fPT1MZABx0cwvfMt2w8I6TREVqYoDgkQoJp7i+1hlIBweTNiFcNcaTdWBScYHSv6dnafp7Ne27JQa6q9XyzheqNGA7SJZsdzVKPg=
